//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Langs
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resource
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RatingUniversity.Langs.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Проверочный ключ.
		/// </summary>
		public static string AccountCheckKey
		{
			get
			{
				return ResourceManager.GetString("AccountCheckKey", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Код.
		/// </summary>
		public static string AccountCode
		{
			get
			{
				return ResourceManager.GetString("AccountCode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Подтвердите пароль.
		/// </summary>
		public static string AccountConfirmPassword
		{
			get
			{
				return ResourceManager.GetString("AccountConfirmPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Создать нового пользователя.
		/// </summary>
		public static string AccountCreate
		{
			get
			{
				return ResourceManager.GetString("AccountCreate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to E-mail.
		/// </summary>
		public static string AccountEmail
		{
			get
			{
				return ResourceManager.GetString("AccountEmail", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email имеет не верный формат.
		/// </summary>
		public static string AccountErrEmail
		{
			get
			{
				return ResourceManager.GetString("AccountErrEmail", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Проверочный ключ введен неправильно.
		/// </summary>
		public static string AccountErrKeyNotMatch
		{
			get
			{
				return ResourceManager.GetString("AccountErrKeyNotMatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Длина пароля должна быть хотя бы {2} символов.
		/// </summary>
		public static string AccountErrPasswordLength
		{
			get
			{
				return ResourceManager.GetString("AccountErrPasswordLength", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пароли не совпадают.
		/// </summary>
		public static string AccountErrPasswordNotMatch
		{
			get
			{
				return ResourceManager.GetString("AccountErrPasswordNotMatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поле {0} обязательно к заполнению.
		/// </summary>
		public static string AccountErrRequired
		{
			get
			{
				return ResourceManager.GetString("AccountErrRequired", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пользователь с таким {0} уже зарегистрирован.
		/// </summary>
		public static string AccountErrUnique
		{
			get
			{
				return ResourceManager.GetString("AccountErrUnique", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ВУЗ уже зарегистрирован.
		/// </summary>
		public static string AccountErrUniversityExist
		{
			get
			{
				return ResourceManager.GetString("AccountErrUniversityExist", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Вход.
		/// </summary>
		public static string AccountLogin
		{
			get
			{
				return ResourceManager.GetString("AccountLogin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Выход.
		/// </summary>
		public static string AccountLogout
		{
			get
			{
				return ResourceManager.GetString("AccountLogout", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Пароль.
		/// </summary>
		public static string AccountPassword
		{
			get
			{
				return ResourceManager.GetString("AccountPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Регистрация.
		/// </summary>
		public static string AccountRegister
		{
			get
			{
				return ResourceManager.GetString("AccountRegister", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to запомнить меня?.
		/// </summary>
		public static string AccountRememberMe
		{
			get
			{
				return ResourceManager.GetString("AccountRememberMe", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Высшее учебеное заведение.
		/// </summary>
		public static string AccountUniversity
		{
			get
			{
				return ResourceManager.GetString("AccountUniversity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Прикрепить файл.
		/// </summary>
		public static string AttachFile
		{
			get
			{
				return ResourceManager.GetString("AttachFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Подробнее.
		/// </summary>
		public static string ButtonLearnMore
		{
			get
			{
				return ResourceManager.GetString("ButtonLearnMore", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to выберите файл.
		/// </summary>
		public static string ChooseFile
		{
			get
			{
				return ResourceManager.GetString("ChooseFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to о степени цитирования (количество ссылок на опубликованные материалы).
		/// </summary>
		public static string CitatDataHeader
		{
			get
			{
				return ResourceManager.GetString("CitatDataHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. автора (ов).
		/// </summary>
		public static string CitatFIO
		{
			get
			{
				return ResourceManager.GetString("CitatFIO", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название опубликованного материала и на каком языке.
		/// </summary>
		public static string CitatInfo
		{
			get
			{
				return ResourceManager.GetString("CitatInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Интернет-адрес (Гипер ссылка) опубликованных материалов в Google Scholar
		///или других международных поисковых системах.
		/// </summary>
		public static string CitatLink
		{
			get
			{
				return ResourceManager.GetString("CitatLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (автор работает в вузе на протяжении многих лет).
		/// </summary>
		public static string CitatNote
		{
			get
			{
				return ResourceManager.GetString("CitatNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название источника (журнал, книга или др.), год издания (номер журнала).
		/// </summary>
		public static string CitatSource
		{
			get
			{
				return ResourceManager.GetString("CitatSource", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Выявление количества спросов на материалы, опубликованные в Google Scholar или других поисковых системах.
		/// </summary>
		public static string CitatUsage
		{
			get
			{
				return ResourceManager.GetString("CitatUsage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Всего.
		/// </summary>
		public static string Common
		{
			get
			{
				return ResourceManager.GetString("Common", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Скачать шаблон.
		/// </summary>
		public static string DownloadTemplate
		{
			get
			{
				return ResourceManager.GetString("DownloadTemplate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер регистрации сертификата (патента)*.
		/// </summary>
		public static string EfNIRCode
		{
			get
			{
				return ResourceManager.GetString("EfNIRCode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to АКТы внедрения.
		/// </summary>
		public static string EfNIRDalolatnoma
		{
			get
			{
				return ResourceManager.GetString("EfNIRDalolatnoma", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to о получении профессорами-преподавателями в текущем году сертификатов (патентов) на интеллектуальную собственность и полученных от организаций актов (о внедрении).
		/// </summary>
		public static string EfNIRDataHeader
		{
			get
			{
				return ResourceManager.GetString("EfNIRDataHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. профессоров-преподавателей основного штата.
		/// </summary>
		public static string EfNIRFIO
		{
			get
			{
				return ResourceManager.GetString("EfNIRFIO", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название разработки, полученной АКТа, сертификат (патент).
		/// </summary>
		public static string EfNIRName
		{
			get
			{
				return ResourceManager.GetString("EfNIRName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название предприятия, предоставившего АКТ и дата выдачи.
		/// </summary>
		public static string EfNIROrganization
		{
			get
			{
				return ResourceManager.GetString("EfNIROrganization", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Патенты.
		/// </summary>
		public static string EfNIRPatent
		{
			get
			{
				return ResourceManager.GetString("EfNIRPatent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Сертификаты.
		/// </summary>
		public static string EfNIRSertificate
		{
			get
			{
				return ResourceManager.GetString("EfNIRSertificate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название ВУЗа.
		/// </summary>
		public static string EfNIRUniversityName
		{
			get
			{
				return ResourceManager.GetString("EfNIRUniversityName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название загруженного файла.
		/// </summary>
		public static string FileName
		{
			get
			{
				return ResourceManager.GetString("FileName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Все права защищены..
		/// </summary>
		public static string FooterCopyrightAllRightReserved
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightAllRightReserved", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Разработано.
		/// </summary>
		public static string FooterCopyrightDev
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightDev", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Государственный Центр Тестирования.
		/// </summary>
		public static string FooterCopyrightDtm
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightDtm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to При полном или частичном использовании материалов ссылка на ресурс обязательна.
		/// </summary>
		public static string FooterCopyrightInfo
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Министерство высшего и среднего специального образования Республики Узбекистан.
		/// </summary>
		public static string FooterCopyrightMinistry
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightMinistry", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Национальный Университет Узбекистана.
		/// </summary>
		public static string FooterCopyrightNuu
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightNuu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to O`zMU.
		/// </summary>
		public static string FooterCopyrightNuuAbbr
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightNuuAbbr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ташкентский Университет Информационных Технологий.
		/// </summary>
		public static string FooterCopyrightTuit
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightTuit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TUIT.
		/// </summary>
		public static string FooterCopyrightTuitAbbr
		{
			get
			{
				return ResourceManager.GetString("FooterCopyrightTuitAbbr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Изменения.
		/// </summary>
		public static string HomePageChanges
		{
			get
			{
				return ResourceManager.GetString("HomePageChanges", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Аналитика.
		/// </summary>
		public static string HomePageChartHeader
		{
			get
			{
				return ResourceManager.GetString("HomePageChartHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Еще немного текста....
		/// </summary>
		public static string HomePageChartHeaderInfo
		{
			get
			{
				return ResourceManager.GetString("HomePageChartHeaderInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Топ ВУЗ-ов Узбекистана.
		/// </summary>
		public static string HomePageHeader
		{
			get
			{
				return ResourceManager.GetString("HomePageHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ресурс запущен .
		/// </summary>
		public static string HomePageHeaderInfo
		{
			get
			{
				return ResourceManager.GetString("HomePageHeaderInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Рейтинг университетов Узбекистана.
		/// </summary>
		public static string HomePageRatingHeader
		{
			get
			{
				return ResourceManager.GetString("HomePageRatingHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Нужно боООоольше текста... .
		/// </summary>
		public static string HomePageRatingHeaderInfo
		{
			get
			{
				return ResourceManager.GetString("HomePageRatingHeaderInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Главная.
		/// </summary>
		public static string HomePageTitle
		{
			get
			{
				return ResourceManager.GetString("HomePageTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название.
		/// </summary>
		public static string HomePageUniversity
		{
			get
			{
				return ResourceManager.GetString("HomePageUniversity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to сведения.
		/// </summary>
		public static string Information
		{
			get
			{
				return ResourceManager.GetString("Information", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to шифр.
		/// </summary>
		public static string InfoThesisCode
		{
			get
			{
				return ResourceManager.GetString("InfoThesisCode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to название.
		/// </summary>
		public static string InfoThesisCodeName
		{
			get
			{
				return ResourceManager.GetString("InfoThesisCodeName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Шифр специального совета.
		/// </summary>
		public static string InfoThesisCouncil
		{
			get
			{
				return ResourceManager.GetString("InfoThesisCouncil", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Почтовый адрес специального совета.
		/// </summary>
		public static string InfoThesisCouncilEmail
		{
			get
			{
				return ResourceManager.GetString("InfoThesisCouncilEmail", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to о защите докторских диссертаций   профессорами-преподавателями основного штата вуза в текущем году.
		/// </summary>
		public static string InfoThesisDataHeader
		{
			get
			{
				return ResourceManager.GetString("InfoThesisDataHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Дата утверждения ВАКом приказа о присвоении ученой степени.
		/// </summary>
		public static string InfoThesisDate
		{
			get
			{
				return ResourceManager.GetString("InfoThesisDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. диссертанта.
		/// </summary>
		public static string InfoThesisFIO
		{
			get
			{
				return ResourceManager.GetString("InfoThesisFIO", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Тема диссертации.
		/// </summary>
		public static string InfoThesisName
		{
			get
			{
				return ResourceManager.GetString("InfoThesisName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Специализация.
		/// </summary>
		public static string InfoThesisSpecialization
		{
			get
			{
				return ResourceManager.GetString("InfoThesisSpecialization", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Место работы (название ВУЗа).
		/// </summary>
		public static string InfoThesisUniversity
		{
			get
			{
				return ResourceManager.GetString("InfoThesisUniversity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to О проекте.
		/// </summary>
		public static string MainMenuAbout
		{
			get
			{
				return ResourceManager.GetString("MainMenuAbout", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Добавить данные.
		/// </summary>
		public static string MainMenuAddData
		{
			get
			{
				return ResourceManager.GetString("MainMenuAddData", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Контакты.
		/// </summary>
		public static string MainMenuContact
		{
			get
			{
				return ResourceManager.GetString("MainMenuContact", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Критерии рейтинга.
		/// </summary>
		public static string MainMenuEduQuality
		{
			get
			{
				return ResourceManager.GetString("MainMenuEduQuality", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Главная.
		/// </summary>
		public static string MainMenuHome
		{
			get
			{
				return ResourceManager.GetString("MainMenuHome", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Рейтинг.
		/// </summary>
		public static string MainMenuRaiting
		{
			get
			{
				return ResourceManager.GetString("MainMenuRaiting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Филиалом какого ВУЗа является.
		/// </summary>
		public static string ManageUniversityBranch
		{
			get
			{
				return ResourceManager.GetString("ManageUniversityBranch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название ВУЗа на русском языке.
		/// </summary>
		public static string ManageUniversityName_RU
		{
			get
			{
				return ResourceManager.GetString("ManageUniversityName_RU", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название ВУЗа на узбекском языке.
		/// </summary>
		public static string ManageUniversityName_UZ
		{
			get
			{
				return ResourceManager.GetString("ManageUniversityName_UZ", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Регион в котором находится.
		/// </summary>
		public static string ManageUniversityRegion
		{
			get
			{
				return ResourceManager.GetString("ManageUniversityRegion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Учебник.
		/// </summary>
		public static string MDUQDarslik
		{
			get
			{
				return ResourceManager.GetString("MDUQDarslik", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ об опубликованных в .
		/// </summary>
		public static string MDUQDataHeader_1
		{
			get
			{
				return ResourceManager.GetString("MDUQDataHeader_1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to году профессорами-преподавателями основного штата монографий, подготовленных к изданию учебников, учебных пособий и учебно-методических комплексов.
		/// </summary>
		public static string MDUQDataHeader_2
		{
			get
			{
				return ResourceManager.GetString("MDUQDataHeader_2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название загруженного файла.
		/// </summary>
		public static string MDUQFileName
		{
			get
			{
				return ResourceManager.GetString("MDUQFileName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. авторов.
		/// </summary>
		public static string MDUQFIO
		{
			get
			{
				return ResourceManager.GetString("MDUQFIO", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Учебно-методический комплекс.
		/// </summary>
		public static string MDUQMajmua
		{
			get
			{
				return ResourceManager.GetString("MDUQMajmua", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Монография.
		/// </summary>
		public static string MDUQMonografiya
		{
			get
			{
				return ResourceManager.GetString("MDUQMonografiya", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название.
		/// </summary>
		public static string MDUQName
		{
			get
			{
				return ResourceManager.GetString("MDUQName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер и дата свидетельства о прохождении Координационного Совета.
		/// </summary>
		public static string MDUQNumber
		{
			get
			{
				return ResourceManager.GetString("MDUQNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Учебное пособие.
		/// </summary>
		public static string MDUQQullanma
		{
			get
			{
				return ResourceManager.GetString("MDUQQullanma", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Шифр специальности.
		/// </summary>
		public static string MDUQSpec
		{
			get
			{
				return ResourceManager.GetString("MDUQSpec", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Год издания.
		/// </summary>
		public static string MDUQYear
		{
			get
			{
				return ResourceManager.GetString("MDUQYear", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Рейтинг ВУЗ-ов Узбекистана.
		/// </summary>
		public static string PageTitle
		{
			get
			{
				return ResourceManager.GetString("PageTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число авторов.
		/// </summary>
		public static string PaperAuthorsCount
		{
			get
			{
				return ResourceManager.GetString("PaperAuthorsCount", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Страна публикации зарубежного научного журнала.
		/// </summary>
		public static string PaperCountry
		{
			get
			{
				return ResourceManager.GetString("PaperCountry", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to о публикации научных статей в текущем году в зарубежных научных журналах (аннотации статей в издательствах реферативных журналов).
		/// </summary>
		public static string PaperDataHeader_1
		{
			get
			{
				return ResourceManager.GetString("PaperDataHeader_1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to об опубликованных научных статьях текущего года в местных научных журналах  (научные журналы, признанные ВАКом).
		/// </summary>
		public static string PaperDataHeader_2
		{
			get
			{
				return ResourceManager.GetString("PaperDataHeader_2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. автора.
		/// </summary>
		public static string PaperFIO
		{
			get
			{
				return ResourceManager.GetString("PaperFIO", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Зарубежный научный журнал, с указанием страны.
		/// </summary>
		public static string PaperJournalInfo
		{
			get
			{
				return ResourceManager.GetString("PaperJournalInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название научного журнала.
		/// </summary>
		public static string PaperJournalName
		{
			get
			{
				return ResourceManager.GetString("PaperJournalName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Интернет-адрес (Гипер ссылка) электронной статьи.
		/// </summary>
		public static string PaperLink
		{
			get
			{
				return ResourceManager.GetString("PaperLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название научной статьи.
		/// </summary>
		public static string PaperName
		{
			get
			{
				return ResourceManager.GetString("PaperName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Год издания, страницы.
		/// </summary>
		public static string PaperYear
		{
			get
			{
				return ResourceManager.GetString("PaperYear", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число профессоров-преподавателей.
		/// </summary>
		public static string PPSAmount
		{
			get
			{
				return ResourceManager.GetString("PPSAmount", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ассистенты или преподаватели.
		/// </summary>
		public static string PPSAssistant
		{
			get
			{
				return ResourceManager.GetString("PPSAssistant", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to На основных штатах.
		/// </summary>
		public static string PPSBasicHeader
		{
			get
			{
				return ResourceManager.GetString("PPSBasicHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Основной штат.
		/// </summary>
		public static string PPSBasicStaff
		{
			get
			{
				return ResourceManager.GetString("PPSBasicStaff", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Общие сведения о профессорcко-преподавательском составе, осуществляющем деятельность в ВУЗЕ.
		/// </summary>
		public static string PPSDataHeader
		{
			get
			{
				return ResourceManager.GetString("PPSDataHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Доценты (без ученой степени).
		/// </summary>
		public static string PPSDocent
		{
			get
			{
				return ResourceManager.GetString("PPSDocent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Доценты.
		/// </summary>
		public static string PPSDocentPhD
		{
			get
			{
				return ResourceManager.GetString("PPSDocentPhD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Почасовики.
		/// </summary>
		public static string PPSHourly
		{
			get
			{
				return ResourceManager.GetString("PPSHourly", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Почасовики.
		/// </summary>
		public static string PPSHourlyHeader
		{
			get
			{
				return ResourceManager.GetString("PPSHourlyHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Доктора наук.
		/// </summary>
		public static string PPSphD
		{
			get
			{
				return ResourceManager.GetString("PPSphD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Кандидаты наук.
		/// </summary>
		public static string PPSphDeX
		{
			get
			{
				return ResourceManager.GetString("PPSphDeX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Профессора (без ученой степени).
		/// </summary>
		public static string PPSProfessor
		{
			get
			{
				return ResourceManager.GetString("PPSProfessor", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Профессора.
		/// </summary>
		public static string PPSProfessorPhD
		{
			get
			{
				return ResourceManager.GetString("PPSProfessorPhD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Старшие преподаватели.
		/// </summary>
		public static string PPSTeacher
		{
			get
			{
				return ResourceManager.GetString("PPSTeacher", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Совместители.
		/// </summary>
		public static string PPSVisitingHeader
		{
			get
			{
				return ResourceManager.GetString("PPSVisitingHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Совместители.
		/// </summary>
		public static string PPSVisitingStaff
		{
			get
			{
				return ResourceManager.GetString("PPSVisitingStaff", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Русский.
		/// </summary>
		public static string RU
		{
			get
			{
				return ResourceManager.GetString("RU", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to количество оценок.
		/// </summary>
		public static string T1_2_kol_otvet
		{
			get
			{
				return ResourceManager.GetString("T1_2_kol_otvet", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число студентов, принявших участие в опросе.
		/// </summary>
		public static string T1_2_kol_stud
		{
			get
			{
				return ResourceManager.GetString("T1_2_kol_stud", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to количество вопросов.
		/// </summary>
		public static string T1_2_kol_vopros
		{
			get
			{
				return ResourceManager.GetString("T1_2_kol_vopros", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Новизна учебных материалов и качество их содержания.
		/// </summary>
		public static string T1_2_N1
		{
			get
			{
				return ResourceManager.GetString("T1_2_N1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Организация учебных занятий и качество обучения.
		/// </summary>
		public static string T1_2_N2
		{
			get
			{
				return ResourceManager.GetString("T1_2_N2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Объективность оценки знаний студентов.
		/// </summary>
		public static string T1_2_N3
		{
			get
			{
				return ResourceManager.GetString("T1_2_N3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование высшего образовательного заведения.
		/// </summary>
		public static string T1_2_VUZ
		{
			get
			{
				return ResourceManager.GetString("T1_2_VUZ", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Степень качества образования (по результатам опроса студентов).
		/// </summary>
		public static string T1_2_Zagolovok
		{
			get
			{
				return ResourceManager.GetString("T1_2_Zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число удовлетворительно сдавших ИКТ.
		/// </summary>
		public static string T1_7_akt_soni
		{
			get
			{
				return ResourceManager.GetString("T1_7_akt_soni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число удовлетворительно сдавших иностранный язык.
		/// </summary>
		public static string T1_7_chet_tili_soni
		{
			get
			{
				return ResourceManager.GetString("T1_7_chet_tili_soni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Общее число профессоров-преподавателей.
		/// </summary>
		public static string T1_7_oqituvchi_soni
		{
			get
			{
				return ResourceManager.GetString("T1_7_oqituvchi_soni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название высшего образовательного заведения.
		/// </summary>
		public static string T1_7_otm_nomi
		{
			get
			{
				return ResourceManager.GetString("T1_7_otm_nomi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Степень знания профессорами-преподавателями иностранного языка и ИКТ.
		/// </summary>
		public static string T1_7_zogolovok
		{
			get
			{
				return ResourceManager.GetString("T1_7_zogolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Год.
		/// </summary>
		public static string T1_God
		{
			get
			{
				return ResourceManager.GetString("T1_God", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование вуза.
		/// </summary>
		public static string T1_OtmName
		{
			get
			{
				return ResourceManager.GetString("T1_OtmName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Показатели рейтинга.
		/// </summary>
		public static string T1_Reyting
		{
			get
			{
				return ResourceManager.GetString("T1_Reyting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Страна.
		/// </summary>
		public static string T1_Strana
		{
			get
			{
				return ResourceManager.GetString("T1_Strana", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о 300 лучших зарубежных высших образовательных заведениях.
		/// </summary>
		public static string T1_Zagolovok
		{
			get
			{
				return ResourceManager.GetString("T1_Zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименования дисциплин, обучаемых на иностранном языке.
		/// </summary>
		public static string T10_fan
		{
			get
			{
				return ResourceManager.GetString("T10_fan", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T10_fayl
		{
			get
			{
				return ResourceManager.GetString("T10_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название иностранного языка.
		/// </summary>
		public static string T10_horijiy_til
		{
			get
			{
				return ResourceManager.GetString("T10_horijiy_til", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Документ, являющийся основанием для проведения обучения на иностранном языке, дата с подписью.
		/// </summary>
		public static string T10_hujjat
		{
			get
			{
				return ResourceManager.GetString("T10_hujjat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to код.
		/// </summary>
		public static string T10_kodi
		{
			get
			{
				return ResourceManager.GetString("T10_kodi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to наименование.
		/// </summary>
		public static string T10_nomi
		{
			get
			{
				return ResourceManager.GetString("T10_nomi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Количество обучаемых студентов.
		/// </summary>
		public static string T10_talaba_soni
		{
			get
			{
				return ResourceManager.GetString("T10_talaba_soni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Уровень образования.
		/// </summary>
		public static string T10_talim_bosqichi
		{
			get
			{
				return ResourceManager.GetString("T10_talim_bosqichi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Образовательные направления (специальности) с обучением на иностранном языке.
		/// </summary>
		public static string T10_yonalish
		{
			get
			{
				return ResourceManager.GetString("T10_yonalish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о курсах (дисциплинах), проводимых на иностранном языке по образовательному направлению (специальности).
		/// </summary>
		public static string T10_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T10_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Учебник.
		/// </summary>
		public static string T11_darslik
		{
			get
			{
				return ResourceManager.GetString("T11_darslik", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T11_fayl
		{
			get
			{
				return ResourceManager.GetString("T11_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование и шифр специальности.
		/// </summary>
		public static string T11_ixtisoslik
		{
			get
			{
				return ResourceManager.GetString("T11_ixtisoslik", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер и дата выдачи свидетельства о прохождении на Координационном Совете.
		/// </summary>
		public static string T11_kengash
		{
			get
			{
				return ResourceManager.GetString("T11_kengash", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Монография.
		/// </summary>
		public static string T11_monografiya
		{
			get
			{
				return ResourceManager.GetString("T11_monografiya", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. авторов.
		/// </summary>
		public static string T11_muallif
		{
			get
			{
				return ResourceManager.GetString("T11_muallif", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Год издания.
		/// </summary>
		public static string T11_nashr_yili
		{
			get
			{
				return ResourceManager.GetString("T11_nashr_yili", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название.
		/// </summary>
		public static string T11_nomi
		{
			get
			{
				return ResourceManager.GetString("T11_nomi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Учебное пособие.
		/// </summary>
		public static string T11_oquv_qollanma
		{
			get
			{
				return ResourceManager.GetString("T11_oquv_qollanma", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Учебно-методический комплекс.
		/// </summary>
		public static string T11_oquv_uslubiy_majmua
		{
			get
			{
				return ResourceManager.GetString("T11_oquv_uslubiy_majmua", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о публикации монографий профессорами –преподавателями основного штата в 2015 году.
		/// </summary>
		public static string T11_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T11_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер и число приказа.
		/// </summary>
		public static string T18_buyruq
		{
			get
			{
				return ResourceManager.GetString("T18_buyruq", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Дисциплина преподавания.
		/// </summary>
		public static string T18_fan
		{
			get
			{
				return ResourceManager.GetString("T18_fan", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. профессоров-преподавателей основного штата.
		/// </summary>
		public static string T18_fish
		{
			get
			{
				return ResourceManager.GetString("T18_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование средних специальных, профессиональных образовательных заведений.
		/// </summary>
		public static string T18_khk
		{
			get
			{
				return ResourceManager.GetString("T18_khk", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to должность.
		/// </summary>
		public static string T18_lavozim
		{
			get
			{
				return ResourceManager.GetString("T18_lavozim", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to совместительство.
		/// </summary>
		public static string T18_orindosh
		{
			get
			{
				return ResourceManager.GetString("T18_orindosh", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to почасовик.
		/// </summary>
		public static string T18_soatbay
		{
			get
			{
				return ResourceManager.GetString("T18_soatbay", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CВЕДЕНИЯ о профессорах-преподавателях, работающих по совместительству в средних специальных, профессиональных образовательных заведениях.
		/// </summary>
		public static string T18_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T18_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Диплом.
		/// </summary>
		public static string T19_diplom
		{
			get
			{
				return ResourceManager.GetString("T19_diplom", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T19_fayl
		{
			get
			{
				return ResourceManager.GetString("T19_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. студентов.
		/// </summary>
		public static string T19_fish
		{
			get
			{
				return ResourceManager.GetString("T19_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Примечание.
		/// </summary>
		public static string T19_izoh
		{
			get
			{
				return ResourceManager.GetString("T19_izoh", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Место и дата проведения.
		/// </summary>
		public static string T19_joy_sana
		{
			get
			{
				return ResourceManager.GetString("T19_joy_sana", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название конкурса и предметы олимпиады.
		/// </summary>
		public static string T19_olimpiada_fani
		{
			get
			{
				return ResourceManager.GetString("T19_olimpiada_fani", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Занявшие места.
		/// </summary>
		public static string T19_orni
		{
			get
			{
				return ResourceManager.GetString("T19_orni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование вуза.
		/// </summary>
		public static string T19_otm
		{
			get
			{
				return ResourceManager.GetString("T19_otm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to номер.
		/// </summary>
		public static string T19_raqam
		{
			get
			{
				return ResourceManager.GetString("T19_raqam", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Республиканские предметные олимпиады  и престижные конкурсы ( в соответствии с направлениями вуза).
		/// </summary>
		public static string T19_respublika_mos
		{
			get
			{
				return ResourceManager.GetString("T19_respublika_mos", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Республиканские предметные олимпиады и престижные конкурсы ( не соответствующие  направлениям вуза).
		/// </summary>
		public static string T19_respublika_mosmas
		{
			get
			{
				return ResourceManager.GetString("T19_respublika_mosmas", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to серия.
		/// </summary>
		public static string T19_seriya
		{
			get
			{
				return ResourceManager.GetString("T19_seriya", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование награды.
		/// </summary>
		public static string T19_sovrin
		{
			get
			{
				return ResourceManager.GetString("T19_sovrin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Вид конкурса.
		/// </summary>
		public static string T19_tanlov_turi
		{
			get
			{
				return ResourceManager.GetString("T19_tanlov_turi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Международные предметные олимпиады  и престижные конкурсы ( в соответствии с направлениями вуза).
		/// </summary>
		public static string T19_xalqaro_mos
		{
			get
			{
				return ResourceManager.GetString("T19_xalqaro_mos", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Международные предметные олимпиады и престижные конкурсы ( не соответствующие  направлениям вуза).
		/// </summary>
		public static string T19_xalqaro_mosmas
		{
			get
			{
				return ResourceManager.GetString("T19_xalqaro_mosmas", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Названия международных, республиканских олимпиад и престижных конкурсов.
		/// </summary>
		public static string T19_xalqaro_olimpiada_nomi
		{
			get
			{
				return ResourceManager.GetString("T19_xalqaro_olimpiada_nomi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о студентах, занявших призовые места в студенческих международных и республиканских олимпиадах, а также престижных конкурсах и получивших награждения (дипломы).
		/// </summary>
		public static string T19_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T19_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О..
		/// </summary>
		public static string T2_1_fish
		{
			get
			{
				return ResourceManager.GetString("T2_1_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число студентов, получивших положительные оценки при тестировании.
		/// </summary>
		public static string T2_1_ijobiy
		{
			get
			{
				return ResourceManager.GetString("T2_1_ijobiy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование высшего учебного заведения.
		/// </summary>
		public static string T2_1_otm
		{
			get
			{
				return ResourceManager.GetString("T2_1_otm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число студентов, принявших участие в тестировании.
		/// </summary>
		public static string T2_1_soni
		{
			get
			{
				return ResourceManager.GetString("T2_1_soni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Оценка знаний студентов.
		/// </summary>
		public static string T2_1_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T2_1_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование высшего учебного заведения.
		/// </summary>
		public static string T2_2_otm
		{
			get
			{
				return ResourceManager.GetString("T2_2_otm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число опрошенных выпускников.
		/// </summary>
		public static string T2_2_soralgansoni
		{
			get
			{
				return ResourceManager.GetString("T2_2_soralgansoni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Число положительных рецензий работодателей на выпускников.
		/// </summary>
		public static string T2_2_taqrizsoni
		{
			get
			{
				return ResourceManager.GetString("T2_2_taqrizsoni", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Оценка квалификации выпускников по результатам анкетирования работодателей.
		/// </summary>
		public static string T2_2_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T2_2_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T2_fayl
		{
			get
			{
				return ResourceManager.GetString("T2_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. профессоров-преподавателей основного штата.
		/// </summary>
		public static string T2_FISH
		{
			get
			{
				return ResourceManager.GetString("T2_FISH", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер диплома магистра (дипломированный специалист).
		/// </summary>
		public static string T2_magistr_nomer
		{
			get
			{
				return ResourceManager.GetString("T2_magistr_nomer", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Серия диплома магистра (дипломированный специалист).
		/// </summary>
		public static string T2_magistr_seriya
		{
			get
			{
				return ResourceManager.GetString("T2_magistr_seriya", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование вуза, присвоившего ученую степень.
		/// </summary>
		public static string T2_OTM
		{
			get
			{
				return ResourceManager.GetString("T2_OTM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер диплома PhD (кандидат наук, доктор наук).
		/// </summary>
		public static string T2_Phd_nomer
		{
			get
			{
				return ResourceManager.GetString("T2_Phd_nomer", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Серия диплома PhD (кандидат наук, доктор наук).
		/// </summary>
		public static string T2_Phd_seriya
		{
			get
			{
				return ResourceManager.GetString("T2_Phd_seriya", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Номер и дата приказа о приеме на работу.
		/// </summary>
		public static string T2_prikaz
		{
			get
			{
				return ResourceManager.GetString("T2_prikaz", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название специальности.
		/// </summary>
		public static string T2_specialnost
		{
			get
			{
				return ResourceManager.GetString("T2_specialnost", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о профессорах-преподавателях основного штата, имеющих диплом магистра или степень (РhD) 300 лучших зарубежных высших образовательных заведений.
		/// </summary>
		public static string T2_Zagolovok
		{
			get
			{
				return ResourceManager.GetString("T2_Zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T20_fayl
		{
			get
			{
				return ResourceManager.GetString("T20_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Фамилия, имя, отчество.
		/// </summary>
		public static string T20_fish
		{
			get
			{
				return ResourceManager.GetString("T20_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Место трудоустройства: предприятие (организация), с указанием полного названия и почтового индекса.
		/// </summary>
		public static string T20_korxona
		{
			get
			{
				return ResourceManager.GetString("T20_korxona", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Из них, работающие на должностях в соответствии со специальностью.
		/// </summary>
		public static string T20_lavozim
		{
			get
			{
				return ResourceManager.GetString("T20_lavozim", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Поступившие в магистратуру, с полным наименованием образовательного учреждения и указанием почтового индекса.
		/// </summary>
		public static string T20_mag_muassasa
		{
			get
			{
				return ResourceManager.GetString("T20_mag_muassasa", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to наименование образовательного направления.
		/// </summary>
		public static string T20_yonalish_nomi
		{
			get
			{
				return ResourceManager.GetString("T20_yonalish_nomi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Шифр образовательного направления.
		/// </summary>
		public static string T20_yonalish_shifr
		{
			get
			{
				return ResourceManager.GetString("T20_yonalish_shifr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to бакалавриат битирувчилари ва улардан  ўқишни тугатгандан кейин 6 ой мобайнида мутахассислиги бўйича ишга ва таълимнинг кейинги босқичларига ўқишга жойлашганлари ҳақида
		///М А Ъ Л У М О Т.
		/// </summary>
		public static string T20_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T20_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T21_fayl
		{
			get
			{
				return ResourceManager.GetString("T21_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Фамилия, имя, отчество.
		/// </summary>
		public static string T21_fish
		{
			get
			{
				return ResourceManager.GetString("T21_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Место трудоустройства: предприятие (организация и др.), с указанием полного названия и почтового адреса ( с указанием электронной почты).
		/// </summary>
		public static string T21_korxona
		{
			get
			{
				return ResourceManager.GetString("T21_korxona", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Из них, работающие на должностях в соответствии со специальностью.
		/// </summary>
		public static string T21_lavozim
		{
			get
			{
				return ResourceManager.GetString("T21_lavozim", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование специальности.
		/// </summary>
		public static string T21_nomi
		{
			get
			{
				return ResourceManager.GetString("T21_nomi", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Шифр специальности.
		/// </summary>
		public static string T21_shifr
		{
			get
			{
				return ResourceManager.GetString("T21_shifr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о выпускниках магистратуры, их трудоустройстве по специальности в течение 6 месяцев после окончания учебы.
		/// </summary>
		public static string T21_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T21_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Основание (приказ, решение, договор и др).
		/// </summary>
		public static string T5_asos
		{
			get
			{
				return ResourceManager.GetString("T5_asos", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Дисциплина.
		/// </summary>
		public static string T5_dars_beradigan_fan
		{
			get
			{
				return ResourceManager.GetString("T5_dars_beradigan_fan", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Страна и место работы.
		/// </summary>
		public static string T5_davlat
		{
			get
			{
				return ResourceManager.GetString("T5_davlat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T5_fayl
		{
			get
			{
				return ResourceManager.GetString("T5_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О..
		/// </summary>
		public static string T5_Fish
		{
			get
			{
				return ResourceManager.GetString("T5_Fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Специальность.
		/// </summary>
		public static string T5_mutaxassislik
		{
			get
			{
				return ResourceManager.GetString("T5_mutaxassislik", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о преподавателях, приглашенных для проведения занятий из зарубежных образовательных заведений.
		/// </summary>
		public static string T5_Zagolovok
		{
			get
			{
				return ResourceManager.GetString("T5_Zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Основание (приказ, решение, договор и др).
		/// </summary>
		public static string T6_asos
		{
			get
			{
				return ResourceManager.GetString("T6_asos", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Страна.
		/// </summary>
		public static string T6_davlat
		{
			get
			{
				return ResourceManager.GetString("T6_davlat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T6_fayl
		{
			get
			{
				return ResourceManager.GetString("T6_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О..
		/// </summary>
		public static string T6_fish
		{
			get
			{
				return ResourceManager.GetString("T6_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Специальность магистратуры.
		/// </summary>
		public static string T6_magistratura
		{
			get
			{
				return ResourceManager.GetString("T6_magistratura", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Направление обучения.
		/// </summary>
		public static string T6_talimyonalish
		{
			get
			{
				return ResourceManager.GetString("T6_talimyonalish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ об обучающихся иностранных студентах.
		/// </summary>
		public static string T6_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T6_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О. студентов, обучающихся в зарубежных вузах на основании программы обмена.
		/// </summary>
		public static string T7_almashuv_fish
		{
			get
			{
				return ResourceManager.GetString("T7_almashuv_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Документ, являющийся основанием программы обмена, дата с подписью.
		/// </summary>
		public static string T7_almashuv_xujjat
		{
			get
			{
				return ResourceManager.GetString("T7_almashuv_xujjat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Бакалавриат / Магистратура.
		/// </summary>
		public static string T7_bakalavr_magistratura
		{
			get
			{
				return ResourceManager.GetString("T7_bakalavr_magistratura", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Страна и название вуза.
		/// </summary>
		public static string T7_bakalavriat
		{
			get
			{
				return ResourceManager.GetString("T7_bakalavriat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T7_fayl
		{
			get
			{
				return ResourceManager.GetString("T7_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Магистратура.
		/// </summary>
		public static string T7_magistratura
		{
			get
			{
				return ResourceManager.GetString("T7_magistratura", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Страна и название вуза.
		/// </summary>
		public static string T7_xorij_davlat
		{
			get
			{
				return ResourceManager.GetString("T7_xorij_davlat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О иностранных студентов, обучающихся в вузе на основании программы обмена.
		/// </summary>
		public static string T7_xorij_talaba_FISH
		{
			get
			{
				return ResourceManager.GetString("T7_xorij_talaba_FISH", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование образовательного направления (специальности).
		/// </summary>
		public static string T7_xorij_yonalish
		{
			get
			{
				return ResourceManager.GetString("T7_xorij_yonalish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование образовательного направления (специальности).
		/// </summary>
		public static string T7_yonalish
		{
			get
			{
				return ResourceManager.GetString("T7_yonalish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ об участниках программы по обмену с зарубежными вузами.
		/// </summary>
		public static string T7_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T7_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T8_fayl
		{
			get
			{
				return ResourceManager.GetString("T8_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О..
		/// </summary>
		public static string T8_fish
		{
			get
			{
				return ResourceManager.GetString("T8_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Документ, являющийся основанием программы сотрудничества, дата с подписью.
		/// </summary>
		public static string T8_hamkorlik_hujjat
		{
			get
			{
				return ResourceManager.GetString("T8_hamkorlik_hujjat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Названия международных зарубежных конференций и семинаров.
		/// </summary>
		public static string T8_konf_seminar
		{
			get
			{
				return ResourceManager.GetString("T8_konf_seminar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Название зарубежного проекта, выполняемый в сотрудничестве.
		/// </summary>
		public static string T8_loyiha
		{
			get
			{
				return ResourceManager.GetString("T8_loyiha", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Профессора-преподаватели / Студенты.
		/// </summary>
		public static string T8_oqit_stud
		{
			get
			{
				return ResourceManager.GetString("T8_oqit_stud", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Профессора-преподаватели.
		/// </summary>
		public static string T8_prof_oqituvchilar
		{
			get
			{
				return ResourceManager.GetString("T8_prof_oqituvchilar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Студенты (бакалавриат и магистратура).
		/// </summary>
		public static string T8_talabalar
		{
			get
			{
				return ResourceManager.GetString("T8_talabalar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Иностранное государство и название вуза.
		/// </summary>
		public static string T8_xorijiy_davlat
		{
			get
			{
				return ResourceManager.GetString("T8_xorijiy_davlat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Наименование образовательного направления (специальности).
		/// </summary>
		public static string T8_yonalish
		{
			get
			{
				return ResourceManager.GetString("T8_yonalish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ об участниках семинаров и зарубежных международных конференций, зарубежных проектов (в сотрудничестве).
		/// </summary>
		public static string T8_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T8_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Основание (приказ, решение, договор и др).
		/// </summary>
		public static string T9_asos
		{
			get
			{
				return ResourceManager.GetString("T9_asos", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Дисциплина проводимого занятия.
		/// </summary>
		public static string T9_fan
		{
			get
			{
				return ResourceManager.GetString("T9_fan", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Файл.
		/// </summary>
		public static string T9_fayl
		{
			get
			{
				return ResourceManager.GetString("T9_fayl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ф.И.О..
		/// </summary>
		public static string T9_fish
		{
			get
			{
				return ResourceManager.GetString("T9_fish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Специальность.
		/// </summary>
		public static string T9_mutaxassislik
		{
			get
			{
				return ResourceManager.GetString("T9_mutaxassislik", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Зарубежное государство и название вуза.
		/// </summary>
		public static string T9_xorijiy_otm
		{
			get
			{
				return ResourceManager.GetString("T9_xorijiy_otm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to СВЕДЕНИЯ о проведении профессорами-преподавателями занятий (лекций, семинаров и практических занятий) в 300 лучших зарубежных высших образовательных заведениях за последние 3 года.
		/// </summary>
		public static string T9_zagolovok
		{
			get
			{
				return ResourceManager.GetString("T9_zagolovok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Top университет - 300.
		/// </summary>
		public static string Top300
		{
			get
			{
				return ResourceManager.GetString("Top300", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Рейтинг Высших образовательных учреждений.
		/// </summary>
		public static string TopHeader
		{
			get
			{
				return ResourceManager.GetString("TopHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to отправить.
		/// </summary>
		public static string Upload
		{
			get
			{
				return ResourceManager.GetString("Upload", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Узбек.
		/// </summary>
		public static string UZCyrillic
		{
			get
			{
				return ResourceManager.GetString("UZCyrillic", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to O`zbek.
		/// </summary>
		public static string UZLatin
		{
			get
			{
				return ResourceManager.GetString("UZLatin", resourceCulture);
			}
		}
	}
}
