//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RatingUniversity.Langs.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string ButtonLearnMore {
            get {
                return ResourceManager.GetString("ButtonLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права защищены..
        /// </summary>
        public static string FooterCopyrightAllRightReserved {
            get {
                return ResourceManager.GetString("FooterCopyrightAllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработано.
        /// </summary>
        public static string FooterCopyrightDev {
            get {
                return ResourceManager.GetString("FooterCopyrightDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Государственный Центр Тестирования.
        /// </summary>
        public static string FooterCopyrightDtm {
            get {
                return ResourceManager.GetString("FooterCopyrightDtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При полном или частичном использовании материалов ссылка на ресурс обязательна.
        /// </summary>
        public static string FooterCopyrightInfo {
            get {
                return ResourceManager.GetString("FooterCopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Министерство высшего и среднего специального образования Республики Узбекистан.
        /// </summary>
        public static string FooterCopyrightMinistry {
            get {
                return ResourceManager.GetString("FooterCopyrightMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национальный Университет Узбекистана.
        /// </summary>
        public static string FooterCopyrightNuu {
            get {
                return ResourceManager.GetString("FooterCopyrightNuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O`zMU.
        /// </summary>
        public static string FooterCopyrightNuuAbbr {
            get {
                return ResourceManager.GetString("FooterCopyrightNuuAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ташкентский Университет Информационных Технологий.
        /// </summary>
        public static string FooterCopyrightTuit {
            get {
                return ResourceManager.GetString("FooterCopyrightTuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUIT.
        /// </summary>
        public static string FooterCopyrightTuitAbbr {
            get {
                return ResourceManager.GetString("FooterCopyrightTuitAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения.
        /// </summary>
        public static string HomePageChanges {
            get {
                return ResourceManager.GetString("HomePageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналитика.
        /// </summary>
        public static string HomePageChartHeader {
            get {
                return ResourceManager.GetString("HomePageChartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще немного текста....
        /// </summary>
        public static string HomePageChartHeaderInfo {
            get {
                return ResourceManager.GetString("HomePageChartHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ ВУЗ-ов.
        /// </summary>
        public static string HomePageHeader {
            get {
                return ResourceManager.GetString("HomePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какая-нибудь актульная и полезная инфа... Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы, Много-много инфы....
        /// </summary>
        public static string HomePageHeaderInfo {
            get {
                return ResourceManager.GetString("HomePageHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ университетов.
        /// </summary>
        public static string HomePageRatingHeader {
            get {
                return ResourceManager.GetString("HomePageRatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно боООоольше текста... .
        /// </summary>
        public static string HomePageRatingHeaderInfo {
            get {
                return ResourceManager.GetString("HomePageRatingHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string HomePageUniversity {
            get {
                return ResourceManager.GetString("HomePageUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О проекте.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить данные.
        /// </summary>
        public static string MainMenuAddData {
            get {
                return ResourceManager.GetString("MainMenuAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string MainMenuContact {
            get {
                return ResourceManager.GetString("MainMenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критерии рейтинга.
        /// </summary>
        public static string MainMenuEduQuality {
            get {
                return ResourceManager.GetString("MainMenuEduQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MainMenuHome {
            get {
                return ResourceManager.GetString("MainMenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг ВУЗ-ов Узбекистана.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг ВУЗ-ов.
        /// </summary>
        public static string TopHeader {
            get {
                return ResourceManager.GetString("TopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O`zbek.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
    }
}
