//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class granti_po_vidam_issledovaniy
    {
        public int id { get; set; }
        public string tormog_name { get; set; }
        public string buyurtma_name { get; set; }
        public Nullable<bool> fundamental { get; set; }
        public Nullable<bool> amaliy { get; set; }
        public Nullable<bool> innovatsion { get; set; }
        public Nullable<bool> lizenziya { get; set; }
        public Nullable<bool> yarmarka { get; set; }
        public Nullable<double> summa { get; set; }
        public Nullable<int> id_university { get; set; }
        public Nullable<int> year { get; set; }
        public string filename { get; set; }
    
        public virtual university university { get; set; }
    }
}
