//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I15_kolichestvo_izdannih_statey
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I151 { get; set; }
        public Nullable<double> I152 { get; set; }
        public Nullable<double> I153 { get; set; }
        public Nullable<double> I15 { get; set; }
        public Nullable<double> mark { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
