//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I17_summa_finansovih_sredstv_poluchennih_na_nauchnuyu_deyatelnost
    {
        public int ID { get; set; }
        public string name_RU { get; set; }
        public string name_UZ { get; set; }
        public Nullable<double> I171 { get; set; }
        public Nullable<double> I172 { get; set; }
        public Nullable<double> I173 { get; set; }
        public Nullable<double> I174 { get; set; }
        public Nullable<double> I17 { get; set; }
        public Nullable<double> mark { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
