//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I18
    {
        public int ID { get; set; }
        public string name_RU { get; set; }
        public string name_UZ { get; set; }
        public Nullable<double> I181 { get; set; }
        public Nullable<double> I1811 { get; set; }
        public Nullable<double> I182 { get; set; }
        public Nullable<double> I183 { get; set; }
        public Nullable<double> I184 { get; set; }
        public Nullable<double> I185 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
