//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I19
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> Z1 { get; set; }
        public Nullable<double> Z2 { get; set; }
        public Nullable<double> Z3 { get; set; }
        public Nullable<double> Z4 { get; set; }
        public Nullable<double> Z5 { get; set; }
        public Nullable<double> Z { get; set; }
        public Nullable<double> I191 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
