//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I2_1_uroven_kachestva_prepodavaniya
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> T1 { get; set; }
        public Nullable<double> T2 { get; set; }
        public Nullable<double> T3 { get; set; }
        public Nullable<double> I21 { get; set; }
        public Nullable<double> I22 { get; set; }
        public Nullable<double> I23 { get; set; }
        public Nullable<double> I2 { get; set; }
        public Nullable<double> mark { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
