//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitorings
    {
        public int Id { get; set; }
        public Nullable<int> J1 { get; set; }
        public Nullable<int> J2 { get; set; }
        public Nullable<int> J3 { get; set; }
        public Nullable<int> J4 { get; set; }
        public Nullable<int> J5 { get; set; }
        public Nullable<int> J6 { get; set; }
        public Nullable<int> J7 { get; set; }
        public Nullable<int> J8 { get; set; }
        public Nullable<int> J9 { get; set; }
        public Nullable<int> J10 { get; set; }
        public Nullable<int> J11 { get; set; }
        public Nullable<int> J12 { get; set; }
        public Nullable<int> J13 { get; set; }
        public Nullable<int> J14 { get; set; }
        public Nullable<int> J15 { get; set; }
        public Nullable<int> J16 { get; set; }
        public Nullable<int> J17 { get; set; }
        public Nullable<int> J18 { get; set; }
        public Nullable<int> J19 { get; set; }
        public Nullable<int> J20 { get; set; }
        public Nullable<int> J21 { get; set; }
        public Nullable<int> J22 { get; set; }
        public Nullable<int> J23 { get; set; }
        public Nullable<int> J24 { get; set; }
        public Nullable<int> J25 { get; set; }
        public Nullable<int> J26 { get; set; }
        public Nullable<int> J27 { get; set; }
        public Nullable<int> J28 { get; set; }
        public Nullable<int> J29 { get; set; }
        public Nullable<int> J30 { get; set; }
        public Nullable<int> J31 { get; set; }
        public Nullable<int> J32 { get; set; }
        public Nullable<int> J1_2 { get; set; }
        public Nullable<int> J1_7 { get; set; }
        public Nullable<int> J2_1 { get; set; }
        public Nullable<int> J2_2 { get; set; }
        public int Year { get; set; }
        public int UniverId { get; set; }
        public Nullable<System.DateTime> Srok { get; set; }
    }
}
