//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nalichie_informacii_o_vuze_v_internete
    {
        public int id { get; set; }
        public Nullable<int> id_university { get; set; }
        public Nullable<int> year { get; set; }
        public string vuz_name { get; set; }
        public Nullable<double> vuz_web { get; set; }
        public Nullable<double> vuz_int_rate { get; set; }
        public Nullable<double> vuz_uz_rate { get; set; }
        public Nullable<int> university_id { get; set; }
    
        public virtual university university { get; set; }
    }
}
