//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osnashennost_laboratornim_oborudovaniem
    {
        public int id { get; set; }
        public Nullable<int> id_university { get; set; }
        public Nullable<int> year { get; set; }
        public string nazvaniya_predmetov_s_lab { get; set; }
        public Nullable<int> kolichestvo_lab_zanyatiy { get; set; }
        public Nullable<int> kolichestvo_polnostyu_osnashennih_lab { get; set; }
        public Nullable<int> university_id { get; set; }
        public string napravlenie { get; set; }
        public Nullable<int> university_id1 { get; set; }
    
        public virtual university university { get; set; }
    }
}
