//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raiting
    {
        public int id { get; set; }
        public Nullable<int> id_university { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<double> p { get; set; }
        public Nullable<double> px { get; set; }
        public Nullable<double> py { get; set; }
        public Nullable<double> n1 { get; set; }
        public Nullable<double> n2 { get; set; }
        public Nullable<double> n3 { get; set; }
        public Nullable<double> n41 { get; set; }
        public Nullable<double> n51 { get; set; }
        public Nullable<double> n42 { get; set; }
        public Nullable<double> n52 { get; set; }
        public Nullable<double> n43 { get; set; }
        public Nullable<double> n53 { get; set; }
        public Nullable<double> i2 { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> s1 { get; set; }
        public Nullable<double> s2 { get; set; }
        public Nullable<double> s3 { get; set; }
        public Nullable<double> p1 { get; set; }
        public Nullable<double> p2 { get; set; }
        public Nullable<double> p3 { get; set; }
        public Nullable<double> p4 { get; set; }
        public Nullable<double> p5 { get; set; }
        public Nullable<double> p5_1 { get; set; }
        public Nullable<double> p6 { get; set; }
        public Nullable<double> p6_1 { get; set; }
        public Nullable<double> k1 { get; set; }
        public Nullable<double> k { get; set; }
        public Nullable<double> ty { get; set; }
        public Nullable<double> p7 { get; set; }
        public Nullable<double> p8 { get; set; }
        public Nullable<double> pz { get; set; }
        public Nullable<double> p9 { get; set; }
        public Nullable<double> tsi { get; set; }
        public Nullable<double> tsti { get; set; }
        public Nullable<double> r1 { get; set; }
        public Nullable<double> r { get; set; }
        public Nullable<double> p10 { get; set; }
        public Nullable<double> p11 { get; set; }
        public Nullable<double> p1_2 { get; set; }
        public Nullable<double> p1_3 { get; set; }
        public Nullable<double> p1_4 { get; set; }
        public Nullable<double> p1_5 { get; set; }
        public Nullable<double> s4 { get; set; }
        public Nullable<double> s5 { get; set; }
        public Nullable<double> s7 { get; set; }
        public Nullable<double> s8 { get; set; }
        public Nullable<double> s9 { get; set; }
        public Nullable<double> d { get; set; }
        public Nullable<double> z { get; set; }
        public Nullable<double> v { get; set; }
        public Nullable<double> t4 { get; set; }
        public Nullable<double> t5 { get; set; }
        public Nullable<double> t6 { get; set; }
        public Nullable<double> tL { get; set; }
        public Nullable<double> i { get; set; }
        public Nullable<double> t7 { get; set; }
        public Nullable<double> t8 { get; set; }
        public Nullable<double> ya { get; set; }
        public Nullable<double> kL { get; set; }
        public Nullable<double> a1 { get; set; }
        public Nullable<double> a2 { get; set; }
        public Nullable<double> a3 { get; set; }
        public Nullable<double> a4 { get; set; }
        public Nullable<double> a5 { get; set; }
        public Nullable<double> k2 { get; set; }
        public Nullable<double> m { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> x1 { get; set; }
        public Nullable<double> x2 { get; set; }
        public Nullable<double> x3 { get; set; }
        public Nullable<double> x4 { get; set; }
        public Nullable<double> x5 { get; set; }
        public Nullable<double> x6 { get; set; }
        public Nullable<double> x7 { get; set; }
        public Nullable<double> x8 { get; set; }
        public Nullable<double> x9 { get; set; }
        public Nullable<double> x10 { get; set; }
        public Nullable<double> x11 { get; set; }
        public Nullable<double> x12 { get; set; }
        public Nullable<double> x13 { get; set; }
        public Nullable<double> x14 { get; set; }
        public Nullable<double> x15 { get; set; }
        public Nullable<double> x16 { get; set; }
        public Nullable<double> ra { get; set; }
        public Nullable<double> u { get; set; }
        public Nullable<double> s { get; set; }
        public Nullable<double> p17 { get; set; }
        public Nullable<double> p18 { get; set; }
        public Nullable<double> p19 { get; set; }
        public Nullable<double> p20 { get; set; }
        public Nullable<int> university_id { get; set; }
        public Nullable<int> university_id1 { get; set; }
    
        public virtual university university { get; set; }
        public virtual university university1 { get; set; }
    }
}
