//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAITING_TOTAL
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I1 { get; set; }
        public Nullable<double> I2 { get; set; }
        public Nullable<double> I3 { get; set; }
        public Nullable<double> I4 { get; set; }
        public Nullable<double> mark { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
