//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class summi_mejdunarodnih_grantov
    {
        public int id { get; set; }
        public string grant_name { get; set; }
        public Nullable<double> grant_summa { get; set; }
        public string buyurtma_name { get; set; }
        public Nullable<double> buyurtma_summa { get; set; }
        public Nullable<int> id_university { get; set; }
        public Nullable<int> year { get; set; }
        public string filename { get; set; }
        public Nullable<int> university_id { get; set; }
    
        public virtual university university { get; set; }
    }
}
