//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class URaitingEntities : DbContext
    {
        public URaitingEntities()
            : base("name=URaitingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<I1_dolya_pps_s_uchenoy_stepenyu> I1_dolya_pps_s_uchenoy_stepenyu { get; set; }
        public virtual DbSet<I10_rezultati_attestacii_u_studentov> I10_rezultati_attestacii_u_studentov { get; set; }
        public virtual DbSet<I11_ocenka_kvalifikacii_vipusknikov_rabotodatelyami> I11_ocenka_kvalifikacii_vipusknikov_rabotodatelyami { get; set; }
        public virtual DbSet<I12_dolya_trudoustroennih_vipusknikov> I12_dolya_trudoustroennih_vipusknikov { get; set; }
        public virtual DbSet<I13_kolichestvo_studentov_udostoennih_nagrad> I13_kolichestvo_studentov_udostoennih_nagrad { get; set; }
        public virtual DbSet<I14_citiruemost_publikaciy_pps> I14_citiruemost_publikaciy_pps { get; set; }
        public virtual DbSet<I15_kolichestvo_izdannih_statey> I15_kolichestvo_izdannih_statey { get; set; }
        public virtual DbSet<I16_kolichestvo_sotrudnikov_utverjdennih_vak> I16_kolichestvo_sotrudnikov_utverjdennih_vak { get; set; }
        public virtual DbSet<I17_summa_finansovih_sredstv_poluchennih_na_nauchnuyu_deyatelnost> I17_summa_finansovih_sredstv_poluchennih_na_nauchnuyu_deyatelnost { get; set; }
        public virtual DbSet<I18_effektivnost_provodimih_nauchnih_rabot> I18_effektivnost_provodimih_nauchnih_rabot { get; set; }
        public virtual DbSet<I19_stepen_osnashennosti_laboratoriy_oborudovaniem> I19_stepen_osnashennosti_laboratoriy_oborudovaniem { get; set; }
        public virtual DbSet<I20_obespechennost_irc_uchebnoy_literaturoy> I20_obespechennost_irc_uchebnoy_literaturoy { get; set; }
        public virtual DbSet<I3_kolichestvo_uchebnikov_i_posobiy> I3_kolichestvo_uchebnikov_i_posobiy { get; set; }
        public virtual DbSet<I4_dolya_inostrannih_prepodavateley_i_studentov> I4_dolya_inostrannih_prepodavateley_i_studentov { get; set; }
        public virtual DbSet<I5_uchastie_v_programme_obmena> I5_uchastie_v_programme_obmena { get; set; }
        public virtual DbSet<I6_kolichestvo_uchebnih_kursov_na_inostrannom> I6_kolichestvo_uchebnih_kursov_na_inostrannom { get; set; }
        public virtual DbSet<I7_uroven_angliyskogo_i_ikt_u_pps> I7_uroven_angliyskogo_i_ikt_u_pps { get; set; }
        public virtual DbSet<I8_dolya_pps_prepodayushih_v_zarubejnih_vuzah> I8_dolya_pps_prepodayushih_v_zarubejnih_vuzah { get; set; }
        public virtual DbSet<I9_dolya_pps_prepodayushego_v_sspo> I9_dolya_pps_prepodayushego_v_sspo { get; set; }
        public virtual DbSet<I2_uroven_kachestva_prepodavaniya> I2_uroven_kachestva_prepodavaniya { get; set; }
    }
}
