//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I13_kolichestvo_studentov_udostoennih_nagrad
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I13 { get; set; }
        public Nullable<double> I131 { get; set; }
        public Nullable<double> I132 { get; set; }
        public Nullable<double> I133 { get; set; }
        public Nullable<double> I134 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
