//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I16_kolichestvo_sotrudnikov_utverjdennih_vak
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I16 { get; set; }
        public Nullable<double> I161 { get; set; }
        public Nullable<double> I162 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
