//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I3_kolichestvo_uchebnikov_i_posobiy
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I31 { get; set; }
        public Nullable<double> I32 { get; set; }
        public Nullable<double> I33 { get; set; }
        public Nullable<double> I3 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
