//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I5_uchastie_v_programme_obmena
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I5 { get; set; }
        public Nullable<double> I51 { get; set; }
        public Nullable<double> I52_1 { get; set; }
        public Nullable<double> I52_2 { get; set; }
        public Nullable<double> I53_1 { get; set; }
        public Nullable<double> I53_2 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
