//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I7_uroven_angliyskogo_i_ikt_u_pps
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I7 { get; set; }
        public Nullable<double> I71 { get; set; }
        public Nullable<double> I72 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
