//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingUniversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I8_dolya_pps_prepodayushih_v_zarubejnih_vuzah
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<double> I8 { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
